name: mle-editor
summary: Flexible terminal-based editor.
description: |
  mle is a small, flexible, terminal-based text editor written in C. 
  Notable features include: full Unicode support, syntax highlighting, 
  scriptable rc file, macros, search and replace (PCRE), window 
  splitting, multiple cursors, and integration with various shell 
  commands.
version: 1.4.3
license: Apache-2.0
base: core20
grade: stable
confinement: strict

apps:
  mle:
    command: usr/local/bin/mle

parts:
  mle:
    plugin: make
    source: https://github.com/adsr/mle.git
    source-tag: v1.4.3
    build-packages: [uthash-dev, liblua5.3-dev, libpcre3-dev]
    stage-packages: [liblua5.3-0, libpcre3, fzf, tree, less, perl, universal-ctags]
